#!/usr/bin/python

import socket
import threading
import pygame

racket = ['Left', 'Right', 'Top', 'Bottom']


def acceptationClient(client, tabClient, racket):
	#Donne sa raquette
	empl = len(tabClient) -1
	client.send(racket[empl])
	print(racket[empl])

	print('Got one connexion')

def lancerPartie(client, tabClient):
	# send start command
	client.send(b'True')

	#get the pos
	speed = client.recv(1024)
	print('affiche speed :', speed)
	print(type(speed))
	# send the pos 		
	tabClient.remove(client)
	for i in tabClient:
		client.send(speed)

def main():
	racket = ['Left', 'Right', 'Top', 'Bottom']
	chaussette = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
	chaussette.bind(('127.0.0.1', 4242))
	chaussette.listen(4)

	tabClient = []

	for i in range (0,2):
		client, addr = chaussette.accept()
		tabClient.append(client)
		threading.Thread(target=acceptationClient, args=(client,tabClient,racket,)).start()
	for i in range (0,2):
		client = tabClient[i]
		threading.Thread(target=lancerPartie, args=(client,tabClient,)).start()

main()