#!/usr/bin/python

import socket
import threading

racket = ['Left', 'Right', 'Top', 'Bottom']


def gestionClient(client, tabClient, racket):
	#Donne sa raquette
	empl = len(tabClient) -1
	client.send(racket[empl])
	print(racket[empl])

	print('Got one connexion')


def main():
	racket = ['Left', 'Right', 'Top', 'Bottom']
	chaussette = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
	chaussette.bind(('127.0.0.1', 4243))
	chaussette.listen(4)

	tabClient = []

	for i in range (0,4):
		client, addr = chaussette.accept()
		tabClient.append(client)
		threading.Thread(target=gestionClient, args=(client,tabClient,racket,)).start()

main()