#!/usr/bin/python

import socket

maChaussette = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
maChaussette.connect(('127.0.0.1', 4243))

racket = maChaussette.recv(1024).decode('utf-8')

print(racket)